repos:
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        exclude: (?x)(\.ini$)
        entry: mypy
        language: system
        files: .py
        args: [ --config=mypy.ini ]

-   repo: local
    hooks:
    -   id: black
        name: black
        exclude: (?x)(\.ini$)
        entry: black
        language: system
        files: .py
        args: [ --line-length=120 ]

-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        exclude: (?x)(\.ini$)
        entry: flake8
        language: system
        files: .py
        args: [ --config=.flake8 ]